version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: blogapi_development
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: blogapi_development
      DB_PASSWORD:
      DB_HOST: db
    sidekiq:
      build: .
    volumes:
      - ".:/app"
    links:
      - db
      - redis
    command: bundle exec sidekiq
  redis:
    image: redis:5.0.10  